### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by Michael-F-Ellis** [qui3xote/ottoscript#11]
The WHEN/IF/THEN syntax is clean and easy to understand and the README explanation is clear and concise.

Where and how do entities like `person.tom` and `lights.porch_sconce_lights` get defined?

I'm curious about `IS`.  It's more than a simple equality, right? So does `person.tom IS 'home'` mean

- Boolean property `home` of `person.tom == True`, or does it mean
- Location state string of `person.tom == 'home'?`

**Comment by qui3xote** [comment]
Entities (anything with dot notation) are defined by home assistant - think of them like sql table references.

Your second interpretation is closer to the truth. in OttoScript  attributes are denoted by entity:attr, so it's essentially shorthand for person.tom:state == 'home'.
