### ISSUE TITLE
CASE syntax

### ISSUE THREAD

**Issue by Michael-F-Ellis** [qui3xote/ottoscript#27]
I like the addition of the CASE statement.  FWIW, I think it could be restructured to be more consistent with traditional expectations and, IMO, less noisy.

Instead of
```
CASE
  IF input_boolean.guest_mode == 'on'
    CALL automation.trigger ON automation.welcome_guests
  END
  IF input_boolean.guest_mode == 'off'
    CALL automation.trigger ON automation.welcome_family
  END
  ELSE
    LOCK lock.front_door_lock
    CALL automation.trigger ON automation.intruder_alert
  END
```

Consider
```
SWITCH
  CASE input_boolean.guest_mode == 'on'
    CALL automation.trigger ON automation.welcome_guests

  CASE input_boolean.guest_mode == 'off'
    CALL automation.trigger ON automation.welcome_family
 
  DEFAULT
    LOCK lock.front_door_lock
    CALL automation.trigger ON automation.intruder_alert
END
```

This could be further simplified for switches on a single state variable as follows:
```
SWITCH input_boolean.guest_mode
  CASE 'on'
    CALL automation.trigger ON automation.welcome_guests

  CASE  'off'
    CALL automation.trigger ON automation.welcome_family
 
  DEFAULT
    LOCK lock.front_door_lock
    CALL automation.trigger ON automation.intruder_alert
END
```

The above is patterned after the Go language. It's got the most useful and flexible switch syntax I've encountered.  Take a look at https://yourbasic.org/golang/switch-statement/ for a good summary.

I'd suggest also borrowing the FALLTHROUGH keyword for situations where you need to fire on more than one case.

**Comment by qui3xote** [comment]
Very interesting. I like that a lot - not reusing IF allows me to get rid of the annoying END statements.  I had already wanted to handle the second case you describe - which (again) was made tricky by the reuse of IF. I was literally about to push out v0.4 and make my first big 'hello world' announcement to the HA community. I'm tempted to delay that a day to switch out the keywords (not hard) so that I don't have to make a breaking change later.

**Comment by Michael-F-Ellis** [comment]
Glad it seems appealing.  Your text asked about `fallthrough`.  The Go authors came up with it when they decided to make `switch` behave differently than its C counterpart.

In C, `switch` evaluates every `case` conditional unless it encounters a `break`.   The C authors thought `switch` would typically be used to execute multiple cases.  In most programs, that turns out to be an infrequent use.  Selecting exactly one of many is much more frequent so programmers are forced to put `break` at the end of every `case` -- and omitting the `break` is a frequent source of subtle bugs. Here's a usage example from an [online C tutorial](https://www.tutorialspoint.com/cprogramming/switch_statement_in_c.htm)
```c
switch(grade) {
      case 'A' :
         printf("Excellent!\n" );
         break;
      case 'B' :
      case 'C' :
         printf("Well done\n" );
         break;
      case 'D' :
         printf("You passed\n" );
         break;
      case 'F' :
         printf("Better try again\n" );
         break;
      default :
         printf("Invalid grade\n" );
   }
```
The Go authors decided to fix that. They made `switch` terminate at the first matching case. That eliminates the need to put a `break` at the end of every case but sometimes you do want to continue evaluating cases.  Hence `fallthrough`.  When used it must be the last statement in a `case` body.

Here's the same logic written in Go.

```go
switch grade {
	case 'A':
		fmt.Printf("Excellent!\n")
	case 'B':
		fallthrough
	case 'C':
		fmt.Printf("Well done\n")
	case 'D':
		fmt.Printf("You passed\n")
	case 'F':
		fmt.Printf("Better try again\n")
	default:
		fmt.Printf("Invalid grade\n")
	}
```
